### ISSUE TITLE
Властивості small-to-large у суфіксному масиві та автоматі

### ISSUE THREAD

**Issue by mshcherba-LeetCode** [Petro2806/Notebook#145]
1) є не більше ніж один елемент k є (j, j + lcp], його можна просто знайти в сеті і додати
2) елементи, що належать [j - lcp, j), утворюють арифметичну прогресію, а саме
j-m*d, j-(m-1)*d, j-(m-2)*d, ..., j-2*d, j-d

**Comment by mshcherba-LeetCode** [comment]
https://qoj.ac/contest/894/problem/3856

**Comment by Petro2806** [comment]
хаваю ці факти
