### ISSUE TITLE
Geometry formulas

### ISSUE THREAD

**Issue by Petro2806** [Petro2806/Notebook#152]
1. Median length
2. Bisector length

**Comment by mshcherba-LeetCode** [comment]
Змінити текст до прямої Ейлера.
For a general triangle, the orthocenter H, the centroid G, and the circumcenter O, in this order, lie on the same line (Euler line) and |HG| : |GO| = 2 : 1

**Comment by mshcherba-LeetCode** [comment]
У теоремі Птолемея "if and only if"
