### ISSUE TITLE
FFT

### ISSUE THREAD

**Issue by yaremaStiahar** [Petro2806/Notebook#176]
- u, v в алфавітному порядку в fft
- Позбутися глобальних масивів в multipoint-eval
- Переназвати solve на multipointEval
- Складність fft, inverse, modulo, exp-log, multipoint-eval
- assert у modulo падає у випадку коли a нульовий многочлен
- Явно написати, що робити, якщо пишемо fft в комплексних

**Comment by mshcherba-LeetCode** [comment]
У multipointEval виклики від синків не розділяти на різні рядки

**Comment by mshcherba-LeetCode** [comment]
У bostan-mori замінити виклики fft на виклики mult на випадок не FFT-шного модуля
