### ISSUE TITLE
successive-shortest-path 

### ISSUE THREAD

**Issue by yaremaStiahar** [Petro2806/Notebook#189]
Пофіксити від'ємні ребра, перетестувати

**Comment by Petro2806** [comment]
Протестувати швидкодію на задачі Матвія.

**Comment by mshcherba-LeetCode** [comment]
Старий код з Левітом працює 3.2 секунди: https://algotester.com/uk/ProblemSolution/Display/1721297
Новий код працює 1.5 секунди: https://algotester.com/uk/ProblemSolution/Display/1721291
